// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"xiuxian/internal/biz"
	"xiuxian/internal/conf"
	"xiuxian/internal/data"
	"xiuxian/internal/server"
	"xiuxian/internal/service"
)

// Injectors from wire.go:

func wireApp(config *conf.Config, logger log.Logger) (*kratos.App, func(), error) {
	confServer := conf.ProvideServer(config)
	confData := conf.ProvideData(config)
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	worldRepository := data.NewWorldRepository(dataData)
	worldService, err := biz.NewWorldAuthority(worldRepository)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	worldUsecase := biz.NewWorldUsecase(worldService, logger)
	serviceWorldService := service.NewWorldService(worldUsecase)
	handler := server.NewLegacyHTTPHandler(worldUsecase, confServer)
	httpServer := server.NewHTTPServer(confServer, serviceWorldService, handler, logger)
	grpcServer := server.NewGRPCServer(confServer, serviceWorldService, logger)
	app := newApp(config, logger, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
